server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///student
    username: root
    password: hhxxttxs123
  mvc:
    view:
      prefix: /
      suffix: .jsp